### ISSUE TITLE
Use Parchment mappings for easier API understanding

### ISSUE THREAD

**Issue by ladenedge** [SayWhatSayMon/VeganDelight#14]
I'm fairly new to Minecraft, so not having a fully human-readable API sometimes makes things a bit tough:

![image](https://github.com/SayWhatSayMon/VeganDelight/assets/2699775/6f06482b-42a6-4c1f-ad55-893a00d88569)

With [Parchment mappings](https://parchmentmc.org/) installed, we get a full picture of the API right in the IDE:

![image](https://github.com/SayWhatSayMon/VeganDelight/assets/2699775/0ddf1f8c-3e1c-4909-8c8e-4d15b41d2a68)

Installing parchment is easy, and doesn't seem to have a downside.  Would it be possible to switch?

**Comment by SayWhatSayMon** [comment]
Done with PR.
