### ISSUE TITLE
Applesauce Duplicate

### ISSUE THREAD

**Issue by EndilCrafter** [SayWhatSayMon/VeganDelight#27]
![crafting_shaped_applesauce_bowls_from_bucket](https://github.com/SayWhatSayMon/VeganDelight/assets/135924661/ccde69ff-01be-4707-8ba7-d0109e0da59c)
![crafting_shaped_applesauce_bucket_from_bowls](https://github.com/SayWhatSayMon/VeganDelight/assets/135924661/54df14eb-cfb8-43f6-b6cf-0f6479df6727)

**Comment by danaYatsuta** [comment]
Can confirm this happening in 1.3.2. Semi-related: I don't think these recipes (and the equivalent soy milk recipes) have any reason to be shaped.

**Comment by ssfwuu0721** [comment]
..And I think these recipes could be shapeless
