### ISSUE TITLE
soybeans dont spawn

### ISSUE THREAD

**Issue by Vadewolf** [SayWhatSayMon/VeganDelight#40]
wat biome do soybeans spawn in? asking cause cant find them at all

**Comment by Player005** [comment]
Hi, wild soybeans should spawn in all medium-temperature overworld biomes. This includes for example taiga (spruce) biomes and plains. There are also soybeans in chests (mineshafts, villages and shipwrecks).

Which mod version and minecraft version are you using, and are you on fabric or forge?

**Comment by Vadewolf** [comment]
1.20.1 forge and none spawn in new chunks

**Comment by Vadewolf** [comment]
ok so im an idiot i finally found soybeans but it took me going out over 4000+ blocks from spawn to find them
