### ISSUE TITLE
Add applesauce as a new egg substitute

### ISSUE THREAD

**Issue by ladenedge** [SayWhatSayMon/VeganDelight#5]
As ProudNitro [mentioned on CurseForge](https://www.curseforge.com/minecraft/mc-mods/vegan-delight/comments), applesauce would make a nice (secondary) egg substitute, one that is popular with real-life vegans.

**Comment by ladenedge** [comment]
Heh, spotted in the NYT Crossword this morning:

![image](https://github.com/SayWhatSayMon/VeganDelight/assets/2699775/76975718-18a2-4864-b3d5-16c621cf684c)

**Comment by SayWhatSayMon** [comment]
Added with PR.
