### ISSUE TITLE
make bottled soymilk stackable

### ISSUE THREAD

**Issue by Emmulah** [SayWhatSayMon/VeganDelight#7]
I can turn 1 bucket of soymilk into 4 bottles, which stack when placed in my inventory- but when I use or move one, the stack is broken and they take up 4 separate slots. Could you make them stacks to 16 or something similar?

**Comment by ladenedge** [comment]
I noticed this too and added a little PR for the fix.

**Comment by SayWhatSayMon** [comment]
I added the PR to the next update.
