### ISSUE TITLE
Silken Tofu does not yield a bowl when consumed

### ISSUE THREAD

**Issue by ladenedge** [SayWhatSayMon/VeganDelight#9]
When I eat a silken tofu, the bowl is consumed along with the tofu.  Based on the way other FD meals work, it seems like it should yield a bowl.  It also looks like the code had this in mind:

```java
    public static final RegistryObject<Item> SILKEN_TOFU = ITEMS.register("silken_tofu",
            () -> new Item(new Item.Properties().food(new FoodProperties.Builder()
                    .nutrition(4)
                    .saturationMod(0.4f)
                    .build())
                    .craftRemainder(Items.BUCKET)
                    .stacksTo(16)));
```

Note however that currently neither a bowl _nor_ a bucket is remaindered.

In short: ideally I think we'd see a bowl pop out when silken tofu is consumed.

**Comment by SayWhatSayMon** [comment]
Fixed with PR.
